version: '3.7'

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    environment:
      - NGINX_HOST=sitch.nz
      - NGINX_PORT=80
    expose:
      - 80
    volumes:
      - ./nginx/sitch.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - sig:/var/www
      # - ./nginx/www:/var/www
      - ./nginx/cache:/cache

  matomo:
    image: matomo:4-apache
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  cloudflared:
    image: cloudflare/cloudflared:2022.7.1
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    depends_on:
      - nginx
